<a href="https://colab.research.google.com/github/sidhantmaurya/protot/blob/main/code_from__scratch_on_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This k-Nearest Neighbors tutorial is broken down into 3 parts:

Step 1: Calculate Euclidean Distance.
Step 2: Get Nearest Neighbors.
Step 3: Make Predictions.



In [63]:
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
dataset = iris.frame.values.tolist()

print(dataset[0])
print(type(dataset[0][0]))

[5.1, 3.5, 1.4, 0.2, 0.0]
<class 'float'>


In [64]:
from numpy import sqrt

def eucli(test_row, train_row):
    distance = 0.0
    # train_row ka last element target hai, isliye usko ignore karo
    for i in range(len(train_row) - 1):
        distance += (test_row[i] - train_row[i]) ** 2
    return sqrt(distance)

In [65]:
# LOCATION OF MOST SIMILAR neighbors

def get_neighbors(train,test_row,num_neighbors):
  distances= list()

  for train_row in train:
    dist= eucli(test_row,train_row)
    distances.append((train_row,dist))

  distances.sort(key=lambda tup:tup[1])

  neighbors=list()
  for i in range(num_neighbors):
    neighbors.append(distances[i][0])

  return neighbors



In [66]:
# make prediction  with neighbors

def prediction(train,test_row,num_neighbors):
  neighbors=get_neighbors(train,test_row,num_neighbors)
  output_values=[row[-1] for row in neighbors]
  predict=max(set(output_values), key= output_values.count)

  return predict


In [84]:
row = dataset[50]   # Is row me target already hai

label = prediction(dataset, row, 10)
print("Predicted class:", label)
print("Predicted flower:", iris.target_names[int(label)])

Predicted class: 1.0
Predicted flower: versicolor


In [85]:
neighbors = get_neighbors(dataset, row, 5)

for n in neighbors:
    print(n)

[7.0, 3.2, 4.7, 1.4, 1.0]
[6.9, 3.1, 4.9, 1.5, 1.0]
[6.7, 3.1, 4.7, 1.5, 1.0]
[6.7, 3.1, 4.4, 1.4, 1.0]
[6.8, 2.8, 4.8, 1.4, 1.0]


Predicted class: 1.0
Predicted flower: versicolor


now we use direct knn



In [69]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


In [70]:
iris = load_iris()
x= iris.data
y= iris.target

In [71]:
print(x[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)


In [73]:
knn=KNeighborsClassifier(n_neighbors=5)


In [74]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [75]:
# Find nearest neighbors
distances, indexes = knn.kneighbors(row)


print("\nNearest Neighbors:")
for distance, index in zip(distances[0], indexes[0]):

    print(
        "Distance:",
        distance,
        "Features:",
        X_train[index],
        "Class:",
        iris.target_names[y_train[index]]
    )


Nearest Neighbors:
Distance: 0.0 Features: [5.7 4.4 1.5 0.4] Class: versicolor
Distance: 0.14142135623730964 Features: [4.9 2.5 4.5 1.7] Class: versicolor
Distance: 0.14142135623730995 Features: [6.  2.7 5.1 1.6] Class: versicolor
Distance: 0.1732050807568884 Features: [5.  3.5 1.6 0.6] Class: versicolor
Distance: 0.22360679774997896 Features: [5.  3.5 1.3 0.3] Class: versicolor


In [90]:
y_pred=knn.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(f"accuracy:",accuracy)
# for actual, predicted in zip(y_test, y_pred):
#     print(
#         "Actual:",
#         iris.target_names[actual],
#         " | Predicted:",
#         iris.target_names[predicted]
#     )

accuracy: 0.9666666666666667


In [98]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
